### ISSUE TITLE
Try to build fails with debian/rules

### ISSUE THREAD

**Issue by jmaks** [mypaint/debian#1] opened 2015-08-09 17:57 UTC
There is a log from my terminal

```
git clone https://github.com/mypaint/debian.git                               
Cloning into 'debian'...
remote: Counting objects: 61, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 59

 git submodule update --init --force                                           [2:51:35]
Submodule 'brushlib' () registered for path 'brushlib'

 fakeroot debian/rules binary                                                  
dh_testdir
scons enable_openmp=true
scons: Reading SConscript files ...
building for 'python2.7' (use scons python_binary=xxx to change)
using 'python2.7-config' (use scons python_config=xxx to change)
Delete(["libmypaint-tests.so", "libmypaint-tests.so", "libmypaint.so", "libmypaintlib.so", "libmypaint.a", "libmypaint-tests.a", "lib/_mypaintlib.so"])
Enabling i18n for brushlib in full application build
set umask to 0022 (was 0022)
scons: done reading SConscript files.
scons: Building targets ...
gcc -o brushlib/brushmodes.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/brushmodes.c
gcc -o brushlib/fifo.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/fifo.c
gcc -o brushlib/helpers.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/helpers.c
gcc -o brushlib/mapping.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mapping.c
gcc -o brushlib/mypaint-brush-settings.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-brush-settings.c
gcc -o brushlib/mypaint-brush.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-brush.c
gcc -o brushlib/mypaint-fixed-tiled-surface.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-fixed-tiled-surface.c
gcc -o brushlib/mypaint-rectangle.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-rectangle.c
gcc -o brushlib/mypaint-surface.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-surface.c
gcc -o brushlib/mypaint-tiled-surface.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-tiled-surface.c
gcc -o brushlib/mypaint.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint.c
gcc -o brushlib/operationqueue.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/operationqueue.c
gcc -o brushlib/rng-double.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/rng-double.c
gcc -o brushlib/tilemap.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/tilemap.c
gcc -o brushlib/utils.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/utils.c
ar rc brushlib/libmypaint.a brushlib/brushmodes.os brushlib/fifo.os brushlib/helpers.os brushlib/mapping.os brushlib/mypaint-brush-settings.os brushlib/mypaint-brush.os brushlib/mypaint-fixed-tiled-surface.os brushlib/mypaint-rectangle.os brushlib/mypaint-surface.os brushlib/mypaint-tiled-surface.os brushlib/mypaint.os brushlib/operationqueue.os brushlib/rng-double.os brushlib/tilemap.os brushlib/utils.os
ranlib brushlib/libmypaint.a
g++ -o lib/mypaintlib_wrap.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/mypaintlib_wrap.cc
g++ -o lib/fill.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/fill.cpp
g++ -o lib/eventhack.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/eventhack.cpp
g++ -o lib/gdkpixbuf2numpy.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/gdkpixbuf2numpy.cpp
g++ -o lib/pixops.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/pixops.cpp
g++ -o lib/fastpng.os -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng12 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/pixman-1 -I/usr/lib/pymodules/python2.7/numpy/core/include -I/usr/include/python2.7 lib/fastpng.cpp
gcc -o brushlib/tests/mypaint-test-surface.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/mypaint-test-surface.c
gcc -o brushlib/tests/mypaint-utils-stroke-player.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/mypaint-utils-stroke-player.c
gcc -o brushlib/tests/testutils.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/testutils.c
gcc -o brushlib/tests/mypaint-benchmark.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/mypaint-benchmark.c
ar rc brushlib/libmypaint-tests.a brushlib/tests/mypaint-test-surface.os brushlib/tests/mypaint-utils-stroke-player.os brushlib/tests/testutils.os brushlib/tests/mypaint-benchmark.os
ranlib brushlib/libmypaint-tests.a
g++ -o _mypaintlib.so -O3 -Wl,-z,relro -Wl,-z,origin -fopenmp -pthread -fopenmp -shared -Wl,-rpath=\$ORIGIN lib/mypaintlib_wrap.os lib/fill.os lib/eventhack.os lib/gdkpixbuf2numpy.os lib/pixops.os lib/fastpng.os -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c -lpng12 -llcms2 -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 -lpython2.7
gcc -o brushlib/tests/test-brush-persistence.o -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/test-brush-persistence.c
gcc -o brushlib/tests/test-brush-persistence -O3 -Wl,-z,relro -Wl,-z,origin -fopenmp -Wl,-rpath=\$ORIGIN brushlib/tests/test-brush-persistence.o -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c
gcc -o brushlib/tests/test-details.o -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/test-details.c
gcc -o brushlib/tests/test-details -O3 -Wl,-z,relro -Wl,-z,origin -fopenmp -Wl,-rpath=\$ORIGIN brushlib/tests/test-details.o -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c
gcc -o brushlib/tests/test-fixed-tiled-surface.o -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/test-fixed-tiled-surface.c
gcc -o brushlib/tests/test-fixed-tiled-surface -O3 -Wl,-z,relro -Wl,-z,origin -fopenmp -Wl,-rpath=\$ORIGIN brushlib/tests/test-fixed-tiled-surface.o -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c
gcc -o brushlib/tests/test-rng.o -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wall -g -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib/tests -I/usr/include/json-c -Ibrushlib brushlib/tests/test-rng.c
gcc -o brushlib/tests/test-rng -O3 -Wl,-z,relro -Wl,-z,origin -fopenmp -Wl,-rpath=\$ORIGIN brushlib/tests/test-rng.o -Lbrushlib -lmypaint-tests -lmypaint -lm -ljson-c
scons: done building targets.
# Max-RSS: ~74000 kbytes
MPLCONFIGDIR=`mktemp -d` python tests/test_mypaintlib.py
Traceback (most recent call last):
  File "tests/test_mypaintlib.py", line 11, in <module>
    from lib import mypaintlib, tiledsurface, brush, document, command, helpers
  File "../lib/tiledsurface.py", line 26, in <module>
    import pixbufsurface
  File "../lib/pixbufsurface.py", line 35, in <module>
    u"Unable to construct a vital internal object. "
  File "../lib/gettext.py", line 82, in C_
    result = result.decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
make: *** [build-stamp] Error 1
```

**Comment by achadwick** [comment] 2015-08-09 20:37
Hi - what locale are you using to do the build (just so I understand what's going on here)? Please paste the output of `locale -a` and `locale`.

We probably shouldn't be using any locale other than C for many of the tests, or update the test code to do the full bindtextdomain()/bind_textdomain_codeset()/textdomain() doance for each test. I prefer the former though...

Since this is the same error as mypaint/mypaint#404, I could make an error handler for that function that spots non-UTF8 output from GLib's g_dpgettext2(), since that indicates a lack of proper setup.

**Comment by jmaks** [comment] 2015-08-10 02:07
There is

```
 locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

And

```
 locale -a                                                                    
C
C.UTF-8
en_GB.utf8
en_US.utf8
POSIX
ru_RU.cp1251
ru_RU.koi8r
ru_RU.utf8
russian
```

**Comment by achadwick** [comment] 2015-08-11 14:13
I can't reproduce this error.

Can you provide the information we ask for in https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md#test-the-program-and-report-issues? I'll need to know more about your system, the affected versions of MyPaint, and anything else you think is relevant.

Please also can you paste the output of `env | grep -E 'LANG|LC_'`?

Thanks.

**Comment by achadwick** [comment] 2015-08-11 16:23
Duplicate of mypaint/mypaint#404 unless this is a very different system. Thanks for the report @jmaks - I think you need to upgrade your system substantially - GTK 3.10 at minimum - before you will be able to run the latest development version of MyPaint.

**Closed as completed by achadwick** 2015-08-11 16:23 UTC
Labels: duplicate
